-- Noms de hash d'armes réels (natives GiveWeaponToPed), regroupés par
-- catégorie. Aucun nom inventé.
Config.WeaponCatalog = {
    ['Poing / Pistolets'] = {
        'WEAPON_PISTOL','WEAPON_PISTOL_MK2','WEAPON_COMBATPISTOL','WEAPON_APPISTOL',
        'WEAPON_STUNGUN','WEAPON_PISTOL50','WEAPON_SNSPISTOL','WEAPON_SNSPISTOL_MK2',
        'WEAPON_HEAVYPISTOL','WEAPON_VINTAGEPISTOL','WEAPON_FLAREGUN',
        'WEAPON_MARKSMANPISTOL','WEAPON_REVOLVER','WEAPON_REVOLVER_MK2',
        'WEAPON_DOUBLEACTION','WEAPON_CERAMICPISTOL','WEAPON_NAVYREVOLVER'
    },
    ['SMG'] = {
        'WEAPON_MICROSMG','WEAPON_SMG','WEAPON_SMG_MK2','WEAPON_ASSAULTSMG',
        'WEAPON_COMBATPDW','WEAPON_MACHINEPISTOL','WEAPON_MINISMG'
    },
    ['Fusils à pompe'] = {
        'WEAPON_PUMPSHOTGUN','WEAPON_PUMPSHOTGUN_MK2','WEAPON_SAWNOFFSHOTGUN',
        'WEAPON_ASSAULTSHOTGUN','WEAPON_BULLPUPSHOTGUN','WEAPON_MUSKET',
        'WEAPON_HEAVYSHOTGUN','WEAPON_DBSHOTGUN','WEAPON_AUTOSHOTGUN'
    },
    ['Fusils d\'assaut'] = {
        'WEAPON_ASSAULTRIFLE','WEAPON_ASSAULTRIFLE_MK2','WEAPON_CARBINERIFLE',
        'WEAPON_CARBINERIFLE_MK2','WEAPON_ADVANCEDRIFLE','WEAPON_SPECIALCARBINE',
        'WEAPON_SPECIALCARBINE_MK2','WEAPON_BULLPUPRIFLE','WEAPON_BULLPUPRIFLE_MK2',
        'WEAPON_COMPACTRIFLE'
    },
    ['Mitrailleuses'] = {
        'WEAPON_MG','WEAPON_COMBATMG','WEAPON_COMBATMG_MK2','WEAPON_GUSENBERG'
    },
    ['Sniper'] = {
        'WEAPON_SNIPERRIFLE','WEAPON_HEAVYSNIPER','WEAPON_HEAVYSNIPER_MK2',
        'WEAPON_MARKSMANRIFLE','WEAPON_MARKSMANRIFLE_MK2'
    },
    ['Lourd'] = {
        'WEAPON_RPG','WEAPON_GRENADELAUNCHER','WEAPON_GRENADELAUNCHER_SMOKE',
        'WEAPON_MINIGUN','WEAPON_FIREWORK','WEAPON_RAILGUN',
        'WEAPON_HOMINGLAUNCHER','WEAPON_COMPACTLAUNCHER'
    },
    ['Explosifs / Lancés'] = {
        'WEAPON_GRENADE','WEAPON_BZGAS','WEAPON_MOLOTOV','WEAPON_STICKYBOMB',
        'WEAPON_PROXMINE','WEAPON_SNOWBALL','WEAPON_PIPEBOMB','WEAPON_SMOKEGRENADE',
        'WEAPON_FLARE'
    },
    ['Corps à corps'] = {
        'WEAPON_KNIFE','WEAPON_NIGHTSTICK','WEAPON_HAMMER','WEAPON_BAT',
        'WEAPON_BOTTLE','WEAPON_CROWBAR','WEAPON_GOLFCLUB','WEAPON_HATCHET',
        'WEAPON_KNUCKLE','WEAPON_MACHETE','WEAPON_SWITCHBLADE','WEAPON_WRENCH',
        'WEAPON_BATTLEAXE'
    }
}
